language: ruby
cache: bundler
rvm:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rails db:create db:migrate RAILS_ENV=test
script:
- bundle exec rake
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: hyGpLdNkUUTyzPBtH9mh1tgkwMg7y5pTaD8vjKgicvf7diR2VP1hTdpaNghq1cBxEHxeSyZorTgfLPixXVAiY8c3TW86XE8aVlsXa5ga360SjcmhM3Z6f6fDasc2bdiTE7Erfe5S8PLblCnChcbajhkFqKBYdrqwdx6a9aGFPm2OItEBUrng0lXJm4INN25fRzzMR9Q7GgO3ZnBkqW4HxPAx/oiPw2YAZ9JPhuOS9UvQlciT9nCz97OdrqwY996BF4wvVqrrOFMEJ0z8WUg586ZedsdcXbU7aJtBGu0G71whyD+A1hNNiZmZ3ODVxsCGBFjCmkCFF6mCva8Sb9Dy3PZM6OfBLUcnAfQ9av2AjcXD33IzcfzsXivmJG/Zog9rfGQTYGLQ6UdBZCa1h9IJwDutlM7xNyM9aZQnafeSuvsJIrBeqEuv91ooNqDiR3sMXCKjGSKnqAI+XQlyDZBC6+JclR3VlN53Z9oq6t0UPCfvzmjkHmq7QrEj7Iqd71MUBYoxLkaqWI3nC8nENQvPmeC/tGV63/2m8SeJ+KJSfsyViPYYKuW+AwjOkaJV69yypKt1CE3n+g8w3ll6qDv25K5ZCMEgqTS9vRdr7dMLL8K3kDSRmjfgskoAewKfp/4WL50mQf7e7qbapaxPIMIIdrnoOctEGeWd6LkFS72dzeQ=
  on: development
  app:
    development: jak-sie-masz-slowfood
  run:
  - bundle exec rails db:migrate
