language: ruby
cache: bundler
rvm:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rails db:create db:migrate RAILS_ENV=test
script:
- bundle exec rake
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: X9kttlQlQP35Ubh318SkparDDdf4Qbp+qVMiXiIx3JVp7b/9g3V8hn9/1HEAXq6mkd1HVsnbdA89JacW936VVvbbwANMGBZTdrJ1QeCxVOdGe0lyA2v1vfhFjJi0zkSPMtIeyfCs0AEPhFYqQtQj7VemAZJU7gwGKr4NDs+Xds3naCniPh9zZkOD51luuUjp+iYLBFHBNq6dA4jZozXZSgg+Ay4DN8hoHJo48K84hJsT8duSBn3W/5sfP19ABQzmle8zlygniQFcxd33of29/TV10Qo844KyB/ju3kfaK4AlU38TT2lO9r9nm9rVlyf+X3OPzfD1BuT7iRcRw8Zdm83skEkKKokLh7lJWW0tHsYjcE05jQInEdApL5JcT188ocCIv8I/YoqUGJNCE4zqGsuWl2HWNLVzYJJbLt3AQ62wgUrC0uRrHdTxyrbZpo3UtMV6QzUafDfp/5lgUUiKMqfSIE83lsGav/OdILTBCgcu9IIqgCHHzWyvhu2O/esatf3vKw3Z1/WlNAbQAMKqzyuDbzov0y22t7OCx6y+i/Aq+FGimuQ+Cc6HAapY4pBOi5YfKUvtkExeAMoT2GC3kMBRGClWg5jBBlrk4/7psx7Z2GN6A71p1PSj+b+KwSaP8dZU/XiiQfGtGNL+q+2NCt/DwF3Ppw5X2ga8AKz2SfM=
  on: development
  app:
    development: jak-sie-masz-slowfood
  run:
  - bundle exec rails db:migrate
