language: ruby
cache: bundler
rvm:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rails db:create db:migrate RAILS_ENV=test
script:
- bundle exec rake
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: BS9dRMPI8w3zaneFPL4w3ScxrSwBc+CS8dloIY4dNV1HgOw036WRytEgIeSB9mkxLsZ6ySREQ4uWZxm2TALZU0kvronXTvgRU1WgkTI6Bg+gv6yraAUmPhgeFfpAsH7V78O34mdfX3UWd2njOKODL6JwDdOjiYulth06bsMz9cUxjdXzrdhqWAMbH+MzAVCOVzH/U2dbPWnIZlSW53XcVr0q15ZPN1U0WctRhFFEn5PZHOWzb4W2CLjN/N+J8fJ2x15mVKkVdZ/Uc4/HVg78t+yNu/dNwrOBp1zpskldmZbd+cB7E/NORJ/jhDgOE0egULOykquDxiBLdgVbOyn8OqeQY90vzqor06uCAt4QyWjQg4MDma3JO76lgTHN+MIRzleGS2t+u/szqJRNGPfgylIJ5sIYmq5eSggodmsDRL6eS6VxPZqHJ6a2ssjJgvyne24pjh5o2Cgi/jFBISbRGfcsch8DZnWryGy07a3ZIm1KgudcyBqVj/ESw/3k75csiIa+a4FEJ8Eabvf2WhvEyQSILXt+snKmgK0UPMuIkMw9f7hXiQcNdPBFoipCBmsnLeOeqCsOasAy0Pdn8iv2tram0EBNR8BfsbYyvohLZ+42513CQe5gjhHPkGkKfZU2RSB59PN4k9jx1W2oPP/VGH6aY5lE9YxDQ120334AReg=
  on: development
  app:
    development: jak-sie-masz-slowfood
  run:
  - bundle exec rails db:migrate
