language: ruby
cache: bundler
rvm:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rails db:create db:migrate RAILS_ENV=test
script:
- bundle exec rake
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ow6+V5SLAvl63GGkJ9sekaz7GYLAUlg1oXEGKmdeeKZCPcmvKsLjXadumJwsupX9hwNxsZ0k4ZKkPnhgCGuVyEEKLIsPwUdYL7bCYHIVbdGiVH4R5YOrwmaqSvsyRJU9lq6W/ir798CIbUp94xF6bNHJCCkKH3EE50dVtceZpjoah/mfBYPV2t4VvT4GZrYKp80JoolQhJjMGca+olnJ1FcFrJO+9IYhd5gWYnwt87HcGejXb3CKmxNHAxYUYxJyKd+3gS6UoG8uJBJWmOOfME/MrEU2cl/i5RlYzGAOTebnvkWJoBK5JcN7Z9TBSYIB8dTeRN91rKFuJ6EruLcVTB87h9zPWZDnkucsnhev9ewKHGA10rc4dvmpxLunlzuqH94yIP4kZrMxfa5t1T6touKAgrRauk+KM9iu7Pfg6eT8qLk5+NIKetZcY2tMZN7C1JpKwebJ90e7/IrQOLcXlqtW/qG/aAESpbgt31B4Pz+3lsxAbffw+aVOEf4EKYQbojowPU9C1HE0YnzGgvOdqpgvIDAsZo3PHM4jyr7Y6fd/7mn+usy90vw/gMS8sLUInHXBk/lSXlVJs2s6wumbwm1aLHMJN84emSe5pFakYC9/+aQIyhZcQ4krls2QgGdSHa9FogHf5l9gzffDLlx1Qow5+eHHjk0U5qnPKrgsNz8=
  on: development
  app:
    development: jak-sie-masz-slowfood
  run:
  - bundle exec rails db:migrate
